#!/bin/bash

# teeb labi jargmised kasud arvudega 1-20 ukshaaval
for (( arv=1; arv<21; arv++ ))
do
# kontrollib kas number on 0 voi 1
	if [ $arv -eq 0 -o $arv -eq 1 ]; then
		echo "$arv - ei ole algarv"
	else
		# kui number pole 0 voi 1 proovib arvu jagada 2-ga, kontrollib kas paarisarv
		jagaja=2
		jaak=$(($arv % $jagaja))
		while [ $jaak -ne 0 ]
		# kui arv polnud paaris siis proovib labi ukshaaval kas ta on mingi muu arvu korrutis
		# kui senikaua kui jaak ei saa vastust proovib uuesti
		do
			jagaja=$(($jagaja + 1))
			jaak=$(($arv % $jagaja))
			# kui arvu jagades jagajaga vastus on taisarv loppeb loop
		done
		# kui arv ja jagaja olid lopus vordsed on tegemis algarvuga
		if [ $arv -eq $jagaja ]; then
			echo "$arv - on algarv"
		else
		# kui arv ja jagaja pole vordsed ei ole algarv
			echo "$arv - ei ole algarv"
		fi
	fi
done
# lopp
