#!/bin/bash
# Arvutab mitu täis bussi saab antud reisijatega ja mitu reisijat jääb üle

# Küsib reisijate arvu
echo -n "Sisesta reisijate arv: "
read reisijad

# Küsib bussi kohtade arvu
echo -n "Sisesta bussi kohtade arv: "
read kohad

# Arvutab täis busside arvu
bussid=$(echo "$reisijad/$kohad" | bc)
# Arvutab üle jäänud reisijad
yle_reisijad=$(echo "$reisijad-($bussid*$kohad)" | bc )

# Annab vastuse
echo " "
echo "Täis busse on $bussid ja maha jäi $yle_reisijad reisijat."
