#!/bin/bash

# Tervitus vastavalt ajale

# Sisesta tuntide arv
echo -e "Sisesta tunni aja väärtus: \c"
read aeg

# Kui aeg on vahemikus 6-12 on hommik
if [ $aeg -ge 6 -a $aeg -lt 12 ]
then
	echo "Tere hommikust!"
# Kui aeg on 12-18 on päev
elif [ $aeg -ge 12 -a $aeg -lt 18 ]
then
	echo "Tere päevast!"
# Kui aeg on 18-22 on õhtu
elif [ $aeg -ge 18 -a $aeg -lt 22 ]
then
	echo "Tere õhtust"
# Kui aeg on 22-24 või 0-6 siis on öö
elif [ $aeg -ge 22 -a $aeg -lt 24 ] || [ $aeg -ge 0 -a $aeg -lt 6 ]
then
	echo "Head ööd"
else
# Kui vastus pole vahemikus 0-23 on vale sisend
	echo "Vale sisend"
fi
