#!/bin/bash

# Tervitus vastavalt süsteemi ajale praegusele kasutjale

# kasutaja nimi
nimi=$(whoami)
# Praegune tundide arv
aeg=$(date +%H)

# Kui aeg on vahemikus 6-12 on hommik
if [ $aeg -ge 6 -a $aeg -lt 12 ]
then
	echo "Tere Hommikust $nimi!"
# Kui aeg on 12-18 on päev
elif [ $aeg -ge 12 -a $aeg -lt 18 ]
then
	echo "Tere päevast $nimi!"
# Kui aeg on 18-22 on õhtu
elif [ $aeg -ge 18 -a $aeg -lt 22 ]
then
	echo "Tere õhtust $nimi!"
# Kui aeg on 22-24 või 0-6 siis on öö
else [ $aeg -ge 22 -a $aeg -lt 24 ] || [ $aeg -ge 0 -a $aeg -lt 6 ]
	echo "Head ööd $nimi!"
fi
